<?xml version="1.0" ?>
<robot name="fella" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find unomas)/urdf/common_properties.urdf.xacro"/>
    <xacro:include filename="$(find unomas)/urdf/fella.gazebo.xacro"/>
    <xacro:include filename="$(find unomas)/urdf/wheel.urdf.xacro"/>

    <xacro:property name="r200_cam_rgb_px" value="0.005"/>
    <xacro:property name="r200_cam_rgb_py" value="0.018"/>
    <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
    <xacro:property name="r200_cam_depth_offset" value="0.01"/>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0.03282" rpy="1.5708 0 3.1415"/>
            <geometry>
                <mesh filename="file://$(find unomas)/urdf/meshes/dummy_body.dae"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision name="base_link_collision">
            <origin xyz="0 0 0.03282" rpy="1.5708 0 0"/>
            <geometry>
                <cylinder radius="0.122" length="0.831"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="-0.1 0 0.03282" rpy="0 0 0"/>
            <mass value="20.0"/>
            <inertia
                ixx="1.284"
                ixy="0.0"
                ixz="0.0"
                iyy="0.298"
                iyz="0.0"
                izz="1.284"/>
        </inertial>
    </link>

    <!-- Wheels -->
    <xacro:wheel wheel_id="left" y_pos="0.42" x_pos="0.0"/>
    <xacro:wheel wheel_id="right" y_pos="-0.42" x_pos="0.0"/>
    <!-- back wheels -->
    <xacro:wheel wheel_id="back" y_pos="0.0" x_pos="-0.28"/>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="imu_link"/>

    <joint name="scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan"/>
        <origin xyz="0 0 0.175" rpy="0 0 0"/>
    </joint>

    <joint name="secondary_scan_joint" type="fixed">
        <parent link = "base_link"/>
        <child link="secondary_base_scan"/>
        <origin xyz="0.12374 0.0 0.12374" rpy="0 0.785398 0"/>
    </joint>

    <link name="base_scan">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.04" radius="0.09"/>
            </geometry>
            <material name="dark"/>
        </visual>

        <inertial>
            <mass value="0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001" />
        </inertial>
    </link>


    <link name="secondary_base_scan">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.04" radius="0.09"/>
            </geometry>
            <material name="green"/>
        </visual>

        <inertial>
            <mass value="0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0"
                    izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0.13 0.0 0.03282" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.08 0.05"/>
            </geometry>
            <material name="dark"/>
        </visual>
        <visual>
            <origin xyz="0.015 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder length="0.03" radius="0.02"/>
            </geometry>
            <material name="dark"/>
        </visual>
    </link>

    <joint name="camera_rgb_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_rgb_frame"/>
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_rgb_frame"/>
        <child link="camera_rgb_optical_frame"/>
    </joint>
    <link name="camera_rgb_optical_frame"/>

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame"/>
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
        <parent link="camera_depth_frame"/>
        <child link="camera_depth_optical_frame"/>
    </joint>
    <link name="camera_depth_optical_frame"/>

</robot>